Django_DnD/Django_DnD/urls.py
from django.contrib import admin
from django.urls import path
from main import views
from django.contrib.auth import views as auth_views
from django.contrib.auth import urls
from django.urls.conf import re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio/', views.inicio),
    path('seleccionarNuevosHechizos/<int:character_id>', views.seleccionarNuevosHechizos),
    path('', views.inicio),
    path('crearPersonaje/', views.newCharacter),
    path('seleccionarSubclase/<int:character_id>', views.selectSubclass),
    path('deseleccionarHechizos/<int:character_id>', views.deseleccionarHechizos),
    path('seleccionarHechizos/<int:character_id>', views.selecSpells),
    path('personajeSeleccionado/<int:character_id>', views.personajeSeleccionado),
    path('mostrarHechizos/', views.mostrarHechizos),
    path('searchSpell/',views.searchSpell),
    path('personajeSeleccionado/', views.personajeSeleccionado),
    path('modificarStats/<int:character_id>', views.modificarStats),
    path('personajeSeleccionado/', views.personajeSeleccionado),
    path('recomendarHechizos/<int:character_id>', views.recomendarHechizos),
    path('login/',auth_views.LoginView.as_view(template_name='login.html')),
    path('logout/',auth_views.LogoutView.as_view(template_name='logout.html')),
    re_path(r'^auth/',include(urls)),
    path('signup/', views.SignUp.as_view(success_url="/login"), name='signup'),
#     path('ajax/load-subclass/', views.load_subclass, name='ajax_load_subclass')
]

Django_DnD/main/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.fields.related import ManyToManyField
from django.contrib.auth.models import User

# Create your models here.
class Class(models.Model):
    name = models.CharField(primary_key=True,max_length=20)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "Classes"
    

class Subclass(models.Model):
    name = models.CharField(primary_key=True,max_length=20)
    fromClass = models.ForeignKey("Class",on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "Subclasses"
    

class Character(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=15)
    race = models.ForeignKey("Race",on_delete=models.CASCADE)
    classCharacter = models.ForeignKey("Class",on_delete=models.CASCADE)
    subclass = models.ForeignKey("Subclass",on_delete=models.CASCADE,null=True)
    level = models.IntegerField(validators=[MinValueValidator(0)])
    strength = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)])
    dexterity = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)])
    constitution = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)])
    intelligence = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)])
    wisdom = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)])
    charisma = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)])
    maxHP = models.IntegerField(validators=[MinValueValidator(0)])
    armorClass = models.IntegerField(validators=[MinValueValidator(0)])
    spells = ManyToManyField("Spell")
    
    def __str__(self):
        return self.name

class Race(models.Model):
    name = models.CharField(primary_key=True, max_length=20)
    
    def __str__(self):
        return self.name
    
class Spell(models.Model):
    name = models.CharField(primary_key=True,max_length=20)
    level = models.IntegerField(validators=[MinValueValidator(0)])
    school = models.CharField(max_length=20)
    castingTime = models.CharField(max_length=20)
    components = models.CharField(max_length=40)
    duration = models.CharField(max_length=20)
    range = models.CharField(max_length=30)
    hasRitual = models.BooleanField()
    types = (("Damage",'Damage'),('Healing','Healing'),('Utility','Utility'))
    type = models.CharField(max_length=10,choices=types)
    requireConcentration = models.BooleanField()
    classes = models.ManyToManyField("Class")
    subclasses = models.ManyToManyField("Subclass")
    description = models.TextField()
    
    def __str__(self):
        return self.name

Django_DnD/main/forms.py
from django import forms
from .models import Character,Subclass   
from itertools import chain
from dataclasses import fields
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User

class newCharacter(forms.ModelForm):
    class Meta:
        model = Character
        fields = ['name','classCharacter','race','level','strength','dexterity','constitution',
                  'intelligence','wisdom','charisma','maxHP','armorClass']
        
class selectSubclass(forms.Form):
    subclassSselected = forms.CharField(max_length=50)
        
class modifyStats(forms.Form):
    lvl = forms.IntegerField(required = False,validators=[MinValueValidator(0)])
    str = forms.IntegerField(required = False,validators=[MinValueValidator(0), MaxValueValidator(20)])
    dxt = forms.IntegerField(required = False,validators=[MinValueValidator(0), MaxValueValidator(20)])
    const = forms.IntegerField(required = False,validators=[MinValueValidator(0), MaxValueValidator(20)])
    int = forms.IntegerField(required = False,validators=[MinValueValidator(0), MaxValueValidator(20)])
    wsd = forms.IntegerField(required = False,validators=[MinValueValidator(0), MaxValueValidator(20)])
    cha = forms.IntegerField(required = False,validators=[MinValueValidator(0), MaxValueValidator(20)])
    
class searchSpellByName(forms.Form):
    name = forms.CharField(max_length=20)
    
class recommendSpell(forms.Form):
    name = forms.CharField(max_length=20)

Django_DnD/main/views.py
from django.shortcuts import render
from main import forms
from main.models import Subclass, Class, Character, Spell
from main.cbrs import recommendation
from django.http import HttpResponseRedirect
from .forms import searchSpellByName
from main import models
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.template.context_processors import request
# Create your views here.

def inicio(request):
    characters = models.Character.objects.all()
    return render(request,'inicio.html',{'characters':characters})

def newCharacter(request):
    if request.method == 'POST':
        form = forms.newCharacter(request.POST)
        if form.is_valid():         
            character = form.save(commit=False)
            character.user = request.user
            character.save()
            subclasses = list(Subclass.objects.values_list("fromClass").distinct())
            subclassesAvailables = [subclase[0] for subclase in subclasses]
            if character.classCharacter.name in subclassesAvailables:
                return HttpResponseRedirect("/seleccionarSubclase/"+ str(character.id))
            else:
                return HttpResponseRedirect("/seleccionarHechizos/"+ str(character.id))
    else:
        form = forms.newCharacter()
        
    return render(request,'crearPersonaje.html',{'form':form})

def selectSubclass(request,character_id):
    if request.method == 'POST':
        character = get_object_or_404(models.Character, pk=character_id)
        subclass = get_object_or_404(models.Subclass, pk= request.POST['subclass'])
        character.subclass = subclass
        character.save()
        return HttpResponseRedirect('/seleccionarHechizos/' + str(character.id))
    character = get_object_or_404(models.Character, pk=character_id)
    subclasses = Subclass.objects.filter(fromClass__name = character.classCharacter)
    return render(request,'seleccionarSubclase.html',{'subclasses':subclasses,'character':character})

def selecSpells(request,character_id):
    if request.method == 'POST':
        character = get_object_or_404(models.Character, pk=character_id)
        spellList = list()
        for spell in request.POST.getlist('spellss'):
            spel = get_object_or_404(models.Spell, pk=spell )
            spellList.append(spel)
        character.spells.add(*spellList)
        character.save()
        return HttpResponseRedirect("../")
    character = get_object_or_404(models.Character, pk=character_id)
    charSubClass = character.subclass
    charMaxSpellLevel = (character.level+1) // 2
    charClass = character.classCharacter
    charSpellsNames = character.spells.values_list('name',flat=True)
    if charSubClass:
        spells = Spell.objects.filter(Q(level__lte = charMaxSpellLevel), Q(classes__in = [Class.objects.get(name = charClass)]) | Q(subclasses__in = [Subclass.objects.get(name = charSubClass)])).distinct()
    else:
        spells = Spell.objects.filter(Q(level__lte = charMaxSpellLevel), Q(classes__in = [Class.objects.get(name = charClass)])).distinct()
    
    return render(request,'seleccionarHechizos.html',{'spells':spells,'character':character})
    
def mostrarHechizos(request):
    spells = Spell.objects.all()
    return render(request,'mostrarHechizos.html', {'spells':spells})

def personajeSeleccionado(request,character_id):
    character = get_object_or_404(models.Character, pk=character_id)
    return render(request,'personajeSeleccionado.html/',{'character':character})

def modificarStats(request,character_id):
    if request.method == 'POST':
        form = forms.modifyStats(request.POST)
        if form.is_valid():
            character = get_object_or_404(models.Character, pk=character_id)
            if form.cleaned_data['lvl'] != None : character.level = form.cleaned_data['lvl']
            if form.cleaned_data['str'] != None : character.strength = form.cleaned_data['str']
            if form.cleaned_data['dxt'] != None : character.dexterity = form.cleaned_data['dxt']
            if form.cleaned_data['const'] != None : character.constitution = form.cleaned_data['const']
            if form.cleaned_data['int'] != None : character.intelligence = form.cleaned_data['int']
            if form.cleaned_data['wsd'] != None : character.wisdom = form.cleaned_data['wsd']
            if form.cleaned_data['cha'] != None : character.charisma = form.cleaned_data['cha']
            character.save()
            return HttpResponseRedirect('../personajeSeleccionado/' + str(character_id))
    else:
        form = forms.modifyStats()
    character = get_object_or_404(models.Character, pk=character_id)
    return render(request,'modificarStats.html',{'form':form ,'character':character})

def searchSpell(request):
    if request.method == 'POST':
        form = searchSpellByName(request.POST)
        if form.is_valid():
            spellName = form.cleaned_data['name']
            spells = Spell.objects.filter(name__icontains=spellName)
            return render(request, 'searchSpell.html', {'form': form,'spellName':spellName,'spells':spells})
    else:
        form = searchSpellByName()
    return render(request,'searchSpell.html',{'form': form})

def seleccionarNuevosHechizos(request,character_id):
    if request.method == 'POST':
        character = get_object_or_404(models.Character, pk=character_id)
        spellList = list()
        for spell in request.POST.getlist('spellss'):
            spel = get_object_or_404(models.Spell, pk=spell )
            spellList.append(spel)
        character.spells.add(*spellList)
        character.save()
        return HttpResponseRedirect("../personajeSeleccionado/" + str(character_id))
    character = get_object_or_404(models.Character, pk=character_id)
    charSubClass = character.subclass
    charMaxSpellLevel = (character.level+1) // 2
    charClass = character.classCharacter
    charSpellsNames = character.spells.values_list('name',flat=True)
    if charSubClass:
        spells = Spell.objects.filter(Q(level__lte = charMaxSpellLevel), Q(classes__in = [Class.objects.get(name = charClass)]) | Q(subclasses__in = [Subclass.objects.get(name = charSubClass)])).distinct()
    else:
        spells = Spell.objects.filter(Q(level__lte = charMaxSpellLevel), Q(classes__in = [Class.objects.get(name = charClass)])).distinct()
    spellsNoSelected = []
    for spell in spells:
        if not spell in character.spells.all(): spellsNoSelected.append(spell)
        
    return render(request,'seleccionarNuevosHechizos.html',{'spells':spellsNoSelected,'character':character})

def deseleccionarHechizos(request,character_id):
    if request.method == 'POST':
        character = get_object_or_404(models.Character,pk=character_id)
        spellList = list()
        for spell in request.POST.getlist('spells'):
            hechizo = get_object_or_404(models.Spell,pk=spell)
            spellList.append(hechizo)
        character.spells.remove(*spellList)
        character.save()
        return HttpResponseRedirect("../personajeSeleccionado/" + str(character_id))
    character = get_object_or_404(models.Character,pk=character_id)
    spells = character.spells.all()
    return render(request,'deseleccionarHechizos.html',{'spells':spells,'character':character})


def recomendarHechizos(request,character_id):
    character = get_object_or_404(models.Character,pk=character_id)
    spells = []
    if character.spells.exists():
        spells = recommendation(character)
    return render(request,'recomendarHechizos.html',{'spells': spells,'characterName':character.name,'character':character})

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'
#     def get_success_url(self, request, user):
#         return "/"

Django_DnD/main/templates/CrearPersonaje.html
{% extends 'base.html' %}

{% block encabezado %} <h1> New Character </h1> {% endblock %}

{% block contenido %} 
	<form method='post'>
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit"> Guardar </button> 
	</form>
{% endblock %}

Django_DnD/main/templates/base.html
<!DOCTYPE html>
<html lang='es'>
	<head> 
		<meta charset='utf-8'>
		<title> DnDBuddy </title>
		{% load static %}
		<link rel='stylesheet' href='{% static "css/navigation.css" %}'>
	</head>
	<body>
		<header>
			{% block encabezado %}{% endblock %}
		  	<nav>
		  		<div id="navigation">
			  		<ul>
			  			<li><a href='/inicio'> Home </a></li>
						<li><a href='/crearPersonaje'>New Character</a></li>
						<li><a href='/mostrarHechizos'>Show all spells</a></li>
						<li><a href='/searchSpell'>Search spell</a></li>
					</ul>
				</div>
			</nav>
			{% block navigation %}{% endblock %}
		 </header>
		 <section class=contenido>
		 	{% block contenido %}{% endblock %}
		 </section>
		 <footer>
		 	<p> Voluntary Work AII &copy;2019</p> 
		 </footer>
	</body>
 </html>

Django_DnD/main/templates/crearPersonaje.html
<!DOCTYPE html>
<html lang='es'>
<header>
  	<nav>
  		<ul>
			<li><a href='/inicio'>Inicio</a></li>			
		</ul>
	</nav>
 </header>
{% block content %}
  <h2>New Character</h2>
  <form method="post" id="newCharacter" data-subclass-url="{% url 'ajax_load_subclass' %}" >
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit"> Guardar </button>
  </form>


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_classCharacter").change(function () {
      var url = $("#newCharacter").attr("data-subclass-url");  
      var classId = $(this).val(); 
   	
   	$.ajax({                      
        url: url,                    
        data: {
          'classCharacter': classId
        },
        success: function (data) {
        	$("#id_subclass").html(data);
        	alert(data);
        	
        }
      });

    });
    </script>
    
{% endblock %}

</html>

Django_DnD/main/templates/deseleccionarHechizos.html
{% extends 'personajeSeleccionado.html' %}

{% block encabezado %} <h1> Deselect Spells </h1> {% endblock %}

{% block contenido %}
<form method='post'>
	{% csrf_token %}
	<select multiple="multiple" name="spells">
	{% for spell in spells %}
    	<option  value="{{ spell.name }}">{{ spell.name }}</option>
	{% endfor %}
	</select>
	<button type="submit"> Guardar </button> 
</form>
{% endblock %}

Django_DnD/main/templates/inicio.html
{% extends 'base.html' %}

{% block encabezado %} <h1> Home </h1> {% endblock %}

{% block contenido %}
	{% if user.is_authenticated %}
		<br>
		Hi {{ user.username }}!
		<ul>
		{% for character in characters %}
			{%if character.user.username == user.username %}
				<li><a href="/personajeSeleccionado/{{character.id}}"> {{character.name}} </a></li>
			{% endif %}    		
		{% endfor %}
		</ul>
		<p><a href="{% url 'logout' %}">Logout</a></p>
	{% else %}
		<p>You are not logged in</p>
		<p><a href="/signup">Signup</a></p>
		<p><a href="/login">Login</a></p>
	{% endif %}
{% endblock %}

Django_DnD/main/templates/modificarStats.html
{% extends 'personajeSeleccionado.html' %}

{% block encabezado %} <h1> Modify Stats </h1> {% endblock %}

{% block contenido %} 
<form method='post'>
	{% csrf_token %}
	{{form.as_p}}
	<button type="submit"> Guardar </button> 
</form>
{% endblock %}

Django_DnD/main/templates/mostrarHechizos.html
{% extends 'base.html' %}

{% block encabezado %} <h1> Show Spells </h1> {% endblock %}

{% block contenido %} 
	<h2>Spells</h2>
		<ul>
		{% for spell in spells %}
		  <li><strong>{{spell.name}}</strong>
		  	<ul>
		  		<li>Level: {{spell.level}}</li>
		  		<li>School: {{spell.school}}</li>
		  		<li>Casting time: {{spell.castingTime}}</li>
		  		<li>Duration: {{spell.duration}}</li>
		  		<li>Range: {{spell.range}}</li>
		  		<li>Components: {{spell.components}}</li>
		  		<li>Has Ritual: {{spell.hasRitual}}</li>
		  		<li>Require concentration: {{spell.requireConcentration}}</li>
		  		<li>Type: {{spell.type}}</li>
		  		<li>Description: {{spell.description}}</li>
		  	</ul>	
		  </li>
		  <br>
		{% endfor %}
		</ul>
{% endblock %}

Django_DnD/main/templates/personajeSeleccionado.html
{% extends 'base.html' %}

{% block encabezado %} <h1> Selected Character </h1> {% endblock %}

{% block navigation %} 
	<nav>
		<ul>
			<li><a href="/personajeSeleccionado/{{character.id}}"> Selected Character</a></li>
			<li><a href="/modificarStats/{{character.id}}"> Modify Stats</a></li>
			<li><a href='/seleccionarNuevosHechizos/{{character.id}}'>Select Spells</a></li>
			<li><a href='/deseleccionarHechizos/{{character.id}}'>Deselect Spells</a></li>
			<li><a href='/recomendarHechizos/{{character.id}}'>Recommend Spells</a></li>
		</ul>
	</nav>
	
	<ul>
	<p>
		<li><strong> Name: </strong>{{character.name}} -- <strong>Level: </strong>{{character.level}} </li>
		<li><strong> Class: </strong>{{character.classCharacter}} -- <strong>Subclass: </strong>{{character.subclass}}</li>
	</p>
		
{% endblock %}

{% block contenido %} 
<h2><strong> Stadistics </strong></h2>
	<li> Strength: {{character.strength}} </li>
	<li> Dexterity: {{character.dexterity}} </li>
	<li> Constitution: {{character.constitution}} </li>
	<li> Intelligence: {{character.intelligence}} </li>
	<li> Wisdom: {{character.wisdom}} </li>
	<li> Charisma: {{character.charisma}} </li>
	
	
	<h2><strong> Spells </strong></h2>
	{% for spell in character.spells.all %}
		<li><strong>{{spell.name}}</strong>
		<ul>
		  	<li>Level: {{spell.level}}</li>
		  	<li>School: {{spell.school}}</li>
		  	<li>Casting time: {{spell.castingTime}}</li>
			<li>Duration: {{spell.duration}}</li>
	  		<li>Range: {{spell.range}}</li>
	  		<li>Components: {{spell.components}}</li>
	  		<li>Has Ritual: {{spell.hasRitual}}</li>
	  		<li>Require concentration: {{spell.requireConcentration}}</li>
	  		<li>Type: {{spell.type}}</li>
	  		<li>Description: {{spell.description}}</li>
  		</ul>
		</li>
	{% endfor %}
	</ul>	
{% endblock %}

Django_DnD/main/templates/recomendarHechizos.html
{% extends 'personajeSeleccionado.html' %}

{% block encabezado %} <h1> Recommend Spells </h1> {% endblock %}

{% block contenido %} 
	<br>
	    <h2>Character: {{characterName|capfirst}}</h2>
	    <ul>
	    {% if spells %}
			{% for spell in spells %}
			  <li><strong>{{spell.0.name}}</strong>
			  	<ul>
			  		<li>Level: {{spell.0.level}}</li>
			  		<li>School: {{spell.0.school}}</li>
			  		<li>Casting time: {{spell.0.castingTime}}</li>
			  		<li>Duration: {{spell.0.duration}}</li>
			  		<li>Range: {{spell.0.range}}</li>
			  		<li>Components: {{spell.0.components}}</li>
			  		<li>Has Ritual: {{spell.0.hasRitual}}</li>
			  		<li>Require concentration: {{spell.0.requireConcentration}}</li>
			  		<li>Type: {{spell.0.type}}</li>
			  		<li>Description: {{spell.0.description}}</li>
			  	</ul>	
			  </li>
			  <br>
			{% endfor %}
		{% else %}
			<li> You don't have any selected spells</li>
		{% endif %}
		</ul>
{% endblock %}

Django_DnD/main/templates/searchSpell.html
{% extends 'base.html' %}

{% block encabezado %} <h1> Search Spell </h1> {% endblock %}

{% block contenido %} 
	<br>
	<form method="post">
	    {% csrf_token %}
	    {{ form }}
	    <input type="submit" value="Submit"><br>
	    {% if spells %}
	    <h2>Coincidences from: {{spellName|capfirst}}</h2>
	    {% endif %}
	    <ul>
		{% for spell in spells %}
		  <li><strong>{{spell.name}}</strong>
		  	<ul>
		  		<li>Level: {{spell.level}}</li>
		  		<li>School: {{spell.school}}</li>
		  		<li>Casting time: {{spell.castingTime}}</li>
		  		<li>Duration: {{spell.duration}}</li>
		  		<li>Range: {{spell.range}}</li>
		  		<li>Components: {{spell.components}}</li>
		  		<li>Has Ritual: {{spell.hasRitual}}</li>
		  		<li>Require concentration: {{spell.requireConcentration}}</li>
		  		<li>Type: {{spell.type}}</li>
		  		<li>Description: {{spell.description}}</li>
		  	</ul>	
		  </li>
		  <br>
		{% endfor %}
		</ul>
	</form>
{% endblock %}

Django_DnD/main/templates/seleccionarHechizos.html
{% extends 'personajeSeleccionado.html' %}

{% block encabezado %} <h1> Select Spells </h1> {% endblock %}

{% block navigation %}{% endblock %}

{% block contenido %}
<br>
<form method='post'>
	{% csrf_token %}
	<select multiple="multiple" name="spellss">
	{% for spell in spells %}
    	<option  value="{{ spell.name }}">{{ spell.name }}</option>
	{% endfor %}
	</select>
	<button type="submit"> Guardar </button> 
</form>
{% endblock %}

Django_DnD/main/templates/seleccionarNuevosHechizos.html
{% extends 'personajeSeleccionado.html' %}

{% block encabezado %} <h1> Select Spells </h1> {% endblock %}

{% block contenido %}
<form method='post'>
	{% csrf_token %}
	<select multiple="multiple" name="spellss">
	{% for spell in spells %}
    	<option  value="{{ spell.name }}">{{ spell.name }}</option>
	{% endfor %}
	</select>
	<button type="submit"> Guardar </button> 
</form>
{% endblock %}

Django_DnD/main/templates/seleccionarSubclase.html
{% extends 'base.html' %}

{% block encabezado %} <h1> Select Subclass </h1> {% endblock %}

{% block navigation %}{% endblock %}

{% block contenido %}
<br>
<form method='post'>
	{% csrf_token %}
	<select name="subclass">
	{% for subclass in subclasses %}
    	<option  value="{{ subclass.name }}">{{ subclass.name }}</option>
	{% endfor %}
	</select>
	<button type="submit"> Guardar </button> 
</form>
{% endblock %}

Django_DnD/main/templates/signup.html
{% extends 'base.html' %}

{% block encabezado %} <h1> Signup </h1> {% endblock %}

{% block contenido %} 
		<form method="post">
		    {% csrf_token %}
		    {{ form.as_p }}
		    <button type="submit">Sign up</button>
  		</form>
{% endblock %}